[[redirects]]
	from = "/news"
	to = "/news/welcome.txt"
	query = { op = "first" }
	status = 307
	force = true

[[redirects]]
	from = "/news"
	to = "/news/latest.txt"
	query = { op = "new" }
	status = 307
	force = true
